### PR TITLE
Updating README.md (info for sites)

### PR DESCRIPTION
**Pull request by MerveKaptan**
Okay, I do not know why it appeared like this, sorry about that, slowly learning !  I tried to create a PR specifically for this: 
https://github.com/sct-pipeline/fmri-segmentation/pull/7/commits/ecff66f8b1ab854f90fe31d18c24b25924b43e07  to move the info from google docs to GitHub page as mentioned here: https://github.com/sct-pipeline/fmri-segmentation/issues/2#issue-1500726695

### CODE REVIEW

**Comment by jcohenadad** [comment]
@MerveKaptan can you please write up a meaningful PR title and description, including a link to an issue that this PR solves:
image

Otherwise, I don't know what I am supposed to be reviewing-- thanks

**Comment by MerveKaptan** [comment]
Done, thank you!

**Comment by MerveKaptan** [comment]
Okay, thank you very much, may I merge the pull request now? Then, we can share this with one site and see if everything is clear to them and data is organized as expected!

**Comment by jcohenadad** [comment]
> may I merge the pull request now?

yup! whenever approved, you can merge when you want

**Pull request merged**
